mkdir "C:\Projects\WIFAuthentication\src\Website\_DEV"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\_DEV\DeployedItems.xml" "C:\Projects\WIFAuthentication\src\Website\_DEV\DeployedItems.xml"
mkdir "C:\Projects\WIFAuthentication\src\Website\App_Config\Include"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\App_Config\Include\FedAuthenticator.config" "C:\Projects\WIFAuthentication\src\Website\App_Config\Include\FedAuthenticator.config"
mkdir "C:\Projects\WIFAuthentication\src\Website\bin"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\bin\FedAuthenticator.dll" "C:\Projects\WIFAuthentication\src\Website\bin\FedAuthenticator.dll"
mkdir "C:\Projects\WIFAuthentication\src\Website\bin"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\bin\FedAuthenticator.pdb" "C:\Projects\WIFAuthentication\src\Website\bin\FedAuthenticator.pdb"
mkdir "C:\Projects\WIFAuthentication\src\Website\bin"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\bin\HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll" "C:\Projects\WIFAuthentication\src\Website\bin\HedgehogDevelopment.SitecoreProject.PackageInstallPostProcessor.dll"
mkdir "C:\Projects\WIFAuthentication\src\Website\sitecore modules\shell\FedAuthenticator"
copy /y "C:\Projects\WIFAuthentication\src\Website\temp\__UpgradeHistory\Upgrade_FedAuthenticator.web_20120823T150319813\transactions\sitecore modules\shell\FedAuthenticator\sso.aspx" "C:\Projects\WIFAuthentication\src\Website\sitecore modules\shell\FedAuthenticator\sso.aspx"
